### ISSUE TITLE
"TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by ayophanz** [gs-shop/vue-slick-carousel#102]
When refresh vue it will return error "TypeError: Cannot read property 'length' of undefined" but when you edit on template it will compile and works, how to fix this?
![image](https://user-images.githubusercontent.com/24581584/79186680-e43c6900-7e4c-11ea-8420-749dc62764d4.png)

**Comment by haog1** [comment]
Did you have a empty content inside your `<vue-slick-carsouel />`

**Comment by haog1** [comment]
You need to show your code, can't tell anything by just showing an error here.

**Comment by ayophanz** [comment]
Thanks but my I already fixed this

**Comment by kyuwoo-choi** [comment]
closing this. open this again if you have further discussion.

**Comment by junmindereal** [comment]
@ayophanz  how did you fix it?

**Comment by ESBOL2312** [comment]
> @ayophanz how did you fix it?
<vue-slick-carousel v-bind="settings" v-if="slides.length">
        <div v-for="(item, id) in slides" :key="id" >

**Comment by ESBOL2312** [comment]
> @ayophanz how did you fix it?
`<vue-slick-carousel v-bind="settings" ref="carousel" v-if="slides.length"> 
               <div v-for="(item, id) in slides" :key="id" >`

**Comment by ayophanz** [comment]
Sorry I can't remember how I do it because its long time ago, but I will take a look in my free time and will inform you.

**Comment by junmindereal** [comment]
> Sorry I can't remember how I do it because its long time ago, but I will take a look in my free time and will inform you.

Thanks!

**Comment by junmindereal** [comment]
> > @ayophanz how did you fix it?
> > `<vue-slick-carousel v-bind="settings" ref="carousel" v-if="slides.length">                 <div v-for="(item, id) in slides" :key="id" >`

Thanks!

**Comment by furatamasensei** [comment]
Also happened here. _Failing on refresh, even with an if statement wrapping it_.

```html
<section v-if="product.images.length > 0" class="px-8 pt-12">
  <VueSlickCarousel
    ref="carousel"
    class="-mx-8"
    v-bind="carouselConfig"
    @afterChange="updateCarouselIndex"
  >
    <ExternalImage
      v-for="image in product.images"
      :key="image.url"
      :image-url="image.url"
      :image-alt="image.alternativeText"
      object-fit="object-contain"
    />
  </VueSlickCarousel>
  ...
<section>
```

```
   ╭────────────────────────────────────────────────────────────╮
   │                                                            │
   │   Nuxt @ v2.15.4                                           │
   │                                                            │
   │   ▸ Environment: development                               │
   │   ▸ Rendering:   server-side                               │
   │   ▸ Target:      server                                    │
   │                                                            │
   │   Listening: http://XXX.XXX.XXX.XX:3000/                   │
   │                                                            │
   │   Tailwind Viewer: http://XXX.XXX.XXX.XX:3000/_tailwind/   │
   │                                                            │
   ╰────────────────────────────────────────────────────────────╯
```

```
ERROR  [Vue warn]: Error in created hook: "TypeError: Cannot read property 'length' of undefined"

found in

---> <InnerSlider>
       <VueSlickCarousel>
         <Pages/catalog/Slug.vue> at pages/catalog/_slug.vue
           <Nuxt>
             <Layouts/default.vue> at layouts/default.vue
               <Root>
```

![image](https://user-images.githubusercontent.com/42239243/116795817-d8781f00-ab01-11eb-997d-a99d5e40beb7.png)

**Comment by amrography** [comment]
@pratamatama I think you can't use component inside VueSlickCarousel. You need to directly add html like docs

**Comment by furatamasensei** [comment]
@amrography I'm afraid that is not the case. Tried using `div`s and still having the same error.

**Comment by luizotavior** [comment]
Hi, I had the same problem. I don't know if it will solve your problems, but here it worked.

I'm using Nuxt with the option "Auto import components" active, so I didn't declare any component that I used inside Slick. As I understand it, "Auto Import" doesn't work inside Slick, so I redeclared them and renamed them.

using the example of the colleague above:


```
<template>
 <VueSlickCarousel>
    <ReExternalImage/>
  </VueSlickCarousel>
</template>

<script>
import ReExternalImage from '@/components/ExternalImage'

export default {
  components: {
    ReExternalImage
  },
}
</script>
```
I spent 2 hours trying to make this work...
Hope this solves someone's problem.

Good luck!
And Thanks to Team vue-slick-carousel for this beautiful package, love you guys!

**Comment by jamestylerpatton** [comment]
@luizotavior This fixed it for me. Thank you!

**Comment by loicgeek** [comment]
@luizotavior  thanks

**Comment by YernarT** [comment]
@luizotavior This fixed it for me too. Thank you!
