### ISSUE TITLE
CSS missing from npm run generate

### ISSUE THREAD

**Issue by mattkaye** [gs-shop/vue-slick-carousel#103]
Not sure what I'm not doing right but, my nuxt.config.js file has this:

` /*
   ** Global CSS
   */
  css: ['vue-slick-carousel'],
`

npm run dev works fine, the node_module stylesheets are there. When running generate, they're nowhere in the build. What step am I missing? I've also tried importing the CSS directly in the component as shown in the directions:

`
import 'vue-slick-carousel/dist/vue-slick-carousel.css'
import 'vue-slick-carousel/dist/vue-slick-carousel-theme.css'
`

Thanks!

**Comment by mattkaye** [comment]
Figured it out after a whole day of digging in. I'm using the tailwindcss-module which has purgecss built into it. The slider classes needed to be whitelisted in the nuxt config or they will be stripped from the production build:

`purgeCSS: {
    whitelistPatterns: [/(^slick-)\w+/]
  }
`

Hope this saves someone a few hours 🤦

**Comment by allanShady** [comment]
It's nice to hear that you had alread solved the issue. Do you know that the white list Patterns differ from framework to framework? I'm tryng to solve the same issue as you faced and i'm using gridsome + tailwind.

In gridsome.server.js I added the white list as below 
`const fs = require('fs');
const path = require('path');
const pick = require('lodash.pick');
const { pathPrefix } = require('./gridsome.config')
const nodeExternals = require('webpack-node-externals')

module.exports = function (api, options) {

  api.chainWebpack((config, { isServer }) => {
    if (isServer) {
      config.externals([
        nodeExternals({
          whitelist: [/(^slick-)\w+/] //The white list pattern you suggested
        })
      ])
    }
  })
  
  api.loadSource(store => {
...`

Thanks in advance!

**Comment by mattkaye** [comment]
I don’t know anything about grindstone, but one thing I see off the bat is you’re using the wrong object key. You need to put the regex in whitelistPatterns, not whitelist. That would explain your error message. Whitelist expects an array of strings. Try that?

**Comment by allanShady** [comment]
Thank you! It worked.

**Comment by mattkaye** [comment]
Awesome, glad I could help. 🤓
