### ISSUE TITLE
How can I use this component in a webpage directly with a JS project setup?

### ISSUE THREAD

**Issue by ashishb** [gs-shop/vue-slick-carousel#129]
I imported script `https://unpkg.com/vue-slick-carousel` from CDN but cannot figure out how to register the component and am getting `Unknown custom element: <VueSlickCarousel> - did you register the component correctly?`

**Comment by matdave** [comment]
What I did was I changed the name when I registered the component. E.g. 

`components: { 'vueslickcarousel' : VueSlickCarousel },`

And in my call I referenced it lower case: 

`<vueslickcarousel :arrows="true" :dots="false">`

Something was failing with the camel case.

**Comment by ashishb** [comment]
Thanks @matdave. I ended up writing my own component :)
