### ISSUE TITLE
Css files not loading with Nuxt build

### ISSUE THREAD

**Issue by eventures-io** [gs-shop/vue-slick-carousel#149]
For some reason the css files are not loaded when running Nuxt in production mode. 
There are no issues in dev mode.

I have tried upgrading Nuxt from 2.10 to 2.14, and tried vue-slick-carousel versions 1.05 and 1.0.6, and followed the setup as described in nuxt-vue-slick-carousel-example (https://github.com/kyuwoo-choi/nuxt-vue-slick-carousel-example), to no avail.

There are no build or console errors. 

Does anyone have suggestions as how to look into this issue?

**Comment by boykininteractive** [comment]
I am running into the same problem. @eventures-io , were you able to figure this out?

**Comment by eventures-io** [comment]
@boykininteractive No, had no luck with this one, and didn't get any response on Nuxt forum. 'solved' by putting the library in the source folder.

**Comment by mamaoag** [comment]
@eventures-io 
A hack I did was importing the css files between `/* purgecss start ignore */  `/* purgecss end ignore */`
` in your main css file.

**Comment by moweli** [comment]
> @eventures-io
> A hack I did was importing the css files between `/* purgecss start ignore */ `/* purgecss end ignore */` ` in your main css file.

@mamaoag hi there, i just wondering did you insert the vue-slick-carousel.css from node_module into main.css file with tag:  **/* purgecss start ignore */ /* purgecss end ignore */**?? I've tried it but still not working for me.

**Comment by mamaoag** [comment]
@mohamoud43 
At that time, What I did was added the css files to the main css file. But you can use the transpile option to resolve the issue. Refer to this issue: https://stackoverflow.com/questions/52613136/how-can-i-transpile-a-dependency-in-node-modules-with-nuxt-2

Have a great day.
