### ISSUE TITLE
Improving Web Vitals CLS score

### ISSUE THREAD

**Issue by rizkysyazuli** [gs-shop/vue-slick-carousel#163]
I'm still getting less than ideal CLS (layout shift) from slick carousel.

<img width="540" alt="Jepretan Layar 2021-01-03 pukul 15 44 21" src="https://user-images.githubusercontent.com/152221/103474918-f4311a00-4dda-11eb-9b4c-ebc7fbfdcb38.png">

Funny thing is, the Performance panel did not report any layout/position change as seen in the screenshot above.

I've implemented [css aspect ratio boxes](https://css-tricks.com/aspect-ratio-boxes/) as suggested in [web.dev](https://web.dev/cls/?utm_source=devtools#how-to-improve-cls) to allocate the initial size and prevent child elements (slick-dots, etc) from shifting around. But there's still the issue of this `div.slick-track` thing.

Any ideas would be really helpful.

**Comment by autresrhumbs** [comment]
I have the same issue and no clue how to solve this either.
Would be very helpful if you could provide us some hints here!
Thanks

**Comment by rizkysyazuli** [comment]
@autresrhumbs in the end, i gave up and use something else. here's an [article](https://itnext.io/javascript-sliders-will-kill-your-website-performance-5e4925570e2b) about alternative sliders.

**Comment by krish4u** [comment]
I have the same CLS issue and tried all possible fixes but no luck.

**Comment by ggeorgiev-webolie** [comment]
The problem with Slick is that first images are loaded and then the carousel is initialized. Initially you have all the images as block elements and after initializations they shrink to one element and the content on the bottom moves to fill the gap.

It can be overtaken with adding class with display:none for all but first element, and remove this class after "init" event. yet... not the best solution.

**Comment by krish4u** [comment]
Making `infinite: false` brought down the CLS to 0.

**Comment by mackonen** [comment]
Adding this scss worked perfectly:

`.js-slider {  
  & > .slide:not(:first-child) {
    display: none;
  }
}`

Source: https://trungk18.com/experience/slick-layout-shift/

**Comment by mohsen** [comment]
> Adding this scss worked perfectly:
> 
> `.js-slider { & > .slide:not(:first-child) { display: none; } }`
> 
> Source: https://trungk18.com/experience/slick-layout-shift/

Only works when `slidesToShow` is not greater than 1.
