### ISSUE TITLE
:asNavFor not working when passed as :as-nav-for to VueSlickCarousel component

### ISSUE THREAD

**Issue by PrajapatiDhara1510** [gs-shop/vue-slick-carousel#172]
Hello there,

I am using this plugin in my Nuxt project. I have used eslint-loader and it formats the code automatically as a coding standard. 
So when I pass `:asNavFor` to the `VueSlickCarousel` it automatically formats to this `:as-nav-for`.

After changing to `:as-nav-for` it doesn't work as expected. If I disable eslint and pass `:asNavFor` it works as expected. 

Does anyone know what is the issue?

**Comment by hahuaz** [comment]
This fixed it: "vue/attribute-hyphenation": "off"
