### ISSUE TITLE
TypeError: this.ro is undefined

### ISSUE THREAD

**Issue by Braincoke** [gs-shop/vue-slick-carousel#67]
When creating a new Nuxt project with `npx create-nuxt-app carousel` and following the installation process given in the README.md, the simple example does not work.

The errors are :
```
TypeError: "this.ro is undefined"
    beforeDestroy vue-slick-carousel.umd.js:9800
    VueJS 27
    run es6.promise.js:75
    notify es6.promise.js:92
    flush _microtask.js:18
client.js:76
```

And 
```
ReferenceError: "ResizeObserver is not defined"
    mounted vue-slick-carousel.umd.js:9760
    VueJS 11
    NuxtJS 2
    Babel 8
client.js:76
```

**Comment by angust** [comment]
I'm getting a similar issue with nuxt in safari  13.0.4. Chrome seems fine.

Error details: TypeError: undefined is not an object (evaluating 'this.ro.unobserve').
