### ISSUE TITLE
Carousel not working in bind (V-for)

### ISSUE THREAD

**Issue by henmarba** [gs-shop/vue-slick-carousel#71]
My carousel not working in v-for. When i do get request to api. Im using the Nuxt.js.
It just works with static data. :(

For example:
...
```
data(){
    return {
      slickOptionsDefault: {
        slidesToShow: 3,
        arrows: true,
        dots: false,
        infinite: false
      },
       lastMatchs: null
    }
  },
mounted() {
    axios.get('https://api.dacast.com/v2/package' + this.api_key,  {})
    .then(response => {
        this.lastMatchs = response.data;
    });
  },
```
.....

```
VueSlickCarousel(v-bind="slickOptionsDefault" ref="lastMatchSlide").slider-matchs
   div(v-for="match in lastMatchs")
```

**Error message: Cannot read property 'length' of undefined.**
<img width="1625" alt="Screen Shot 2020-02-23 at 13 58 49" src="https://user-images.githubusercontent.com/50592868/75116204-a5f0ad80-5644-11ea-83ec-094d47f8af85.png">

I would like to continue using this component, is there any solution?

I tested the v-for without Vueslick and it worked.

**Comment by henmarba** [comment]
#

- [ ] 

1. ``

**Comment by kyuwoo-choi** [comment]
@henmarba  could you share the demo for the issue?

**Comment by henmarba** [comment]
@kyuwoo-choi  I managed to resolve it with an asynchronous request. Thanks.

**Comment by aalicki** [comment]
Reviving this issue, could you provide an example of your final solution? Currently running into the same issue with slots, and the current documentation doesn't cover it very well.

Thanks!

**Comment by CamilleScholtz** [comment]
+1
