### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by Narzha** [gs-shop/vue-slick-carousel#72]
Hi, i just imported the component into my project but i cant get the css style to work, it just shows the images one on top of the other.

Here is photo of my code.
[https://imgur.com/r4xZ5mp](url)

**Comment by nitinsinghnaruka** [comment]
Change your CSS path to this

import 'vue-slick-carousel/dist/vue-slick-carousel.css';

**Comment by kyuwoo-choi** [comment]
must import `vue-slick-carousel/dist/vue-slick-carousel.css`
and optional theme, import `vue-slick-carousel-theme.css`
