### ISSUE TITLE
Slider not displaying any elements on the page

### ISSUE THREAD

**Issue by haydenmyers** [gs-shop/vue-slick-carousel#76]
The slider is not showing any elements on the page, despite the code being there when I inspect element.

I have only just installed this component through npm, and have copied and pasted the demo code directly from npm too. However all I get is a blank space. I can perform swipe/drag events in that empty space and it is registering (I know this because I see changed happening when I inspect element) however I cannot actually see anything.

I am calling the component correctly in my html with no console errors.

Any advice please?

**Comment by kyuwoo-choi** [comment]
It's hard to say exactly what the problem is with your explanation.
here's a full demo.
https://codesandbox.io/s/github/kyuwoo-choi/nuxt-vue-slick-carousel-example
wish it helps.

**Comment by joaokrabbe** [comment]
Same problem here.

**Comment by aalicki** [comment]
Can confirm this under the following setup:

Vue Slick Version: **1.0.6**
Vue.JS Version: **2.5.17**
CSS Framework: **Bootstrap 4**

I've been able to get the slider to show up where I expected it to by adding the following CSS, which isn't included in the /src/ CSS file.
```
.slick-slider {
    position: relative;
}
```

Additionally, all of the content / slides appear just at the last "frame" when clicking the left arrow, and they appear to be stacked and unstyled (see: https://github.com/gs-shop/vue-slick-carousel/issues/73)

**Update:**

According to #73  - you MUST import the CSS inside of the component it seems. I was importing the CSS before loading the component, and it didn't seem to work. Regardless, the following line is important to getting the slider displayed:

`import 'vue-slick-carousel/dist/vue-slick-carousel.css';`
