### ISSUE TITLE
Must import vue-slick-carousel.css

### ISSUE THREAD

**Issue by lkhlufo** [gs-shop/vue-slick-carousel#78]
Hi,

Thank you for sharing.
For me, I must include vue-slick-carousel/dist/vue-slick-carousel.css in my component to work.

So, my include part looks like this :

import VueSlickCarousel from 'vue-slick-carousel';
import 'vue-slick-carousel/dist/vue-slick-carousel-theme.css';
import 'vue-slick-carousel/dist/vue-slick-carousel.css';

Nuxt v2.11
Vue v2.6.11

Regards

**Comment by kyuwoo-choi** [comment]
yup. thanks.
I guess you read the outdated doc. recently I updated what you mentioned.
cheers.

**Comment by movitto** [comment]
The docs [here](https://gs-shop.github.io/vue-slick-carousel/#/) are still outdated.
