### ISSUE TITLE
Unable to reach last slide images with infinite off

### ISSUE THREAD

**Issue by RasmusO95** [gs-shop/vue-slick-carousel#85]
Im using 2 sets of slick sliders, where the bottom one is used as the thumbnail to change images for the big slider above.

Im not using the "isNavFor", im listening to events emitted, then manually selecting a new slide image with the goTo function.

But, if i use the following settings:

`    private thumbsOptions: SlickOptions = {
        arrows: true,
        dots: false,
        infinite: false,
        focusOnSelect: true,
        initialSlide: this.activeIndex,
        slidesToShow: 3,
        slidesToScroll: 1,
        lazyLoad: 'ondemand',
        draggable: false
    }`

Then i am unable to ever reach the last 2 slides, as its showing 3 slides but since infinite is false, i cannot get to them. Video below:

https://drive.google.com/uc?id=1eJ6L7pH66MB6nMzBD7t2x4Ja1q3E3Ms1

Am i doing something wrong? Or is there a way to reach the last slides without having infinite turned on? It should just stop when reaching the last index, not when all slides are in the view.

**Comment by kyuwoo-choi** [comment]
It's unable to do that by design I think.
the current slide is leftmost one by default, and disabling infinite won't give you chance to reach the last 2.
I recommend you to enable infinite.
or maybe you can add additional 2, so you can move to the last one.

**Comment by RasmusO95** [comment]
If i add an additional 2 ill just be moving the issue 2 by 2 slides. Unless you were thinking like adding 2 blank slides. 

Anywho, wouldnt it be possible to allow to reach slides by index when navigating instead of by what slide is the left most?

**Comment by davidnoh** [comment]
I stumbled about the same issue. Any ideas for a workaround? Isn't that a behavior the original slick carousel supports? btw. thanks for your work.

**Comment by magebit-mikus** [comment]
This seems like a regression.

**Comment by magebit-mikus** [comment]
This seems like a regression. Original Slick slider supports this feature. Please see Codepen link:
https://codepen.io/magebit-mikus/pen/MWKbRZR

**Comment by RasmusO95** [comment]
Indeed @magebit-mikus the issue should be re-opened

**Comment by seanc** [comment]
Experiencing this as well

**Comment by geancanova** [comment]
I'm with this same problem.

**Comment by LeonardoCesca** [comment]
I'm with this same problem

HELP ME!!

**Comment by mylawacad** [comment]
Same problem. Please, help
