### ISSUE TITLE
Repositioning of Arrow Elements

### ISSUE THREAD

**Issue by rshelnutt** [gs-shop/vue-slick-carousel#88]
Trying to display both the previous/next arrows beneath the slider. 

When using #prevArrow/#nextArrow while templating new elements, the DOM position still renders in the initial, default order:

**[Example]**
```vue
<VueSlickCarousel v-bind="settings">
   <div class="slide-item" v-for="(group, index) in formattedGroups">
      {{`${group.first_name} ${group.last_name}`}}
   </div>
   <template #prevArrow>
      <div class="prevArrow">Prev</div>
   </template>
   <template #nextArrow>
      <div class="nextArrow">Next</div>
   </template>
</VueSlickCarousel>
```
Still renders...
```html
<div class="slick-slider slick-initialized">
   <div class="prevArrow slick-arrow slick-prev slick-disabled">Prev</div>
      <div class="slick-list">
         …
      </div>
   <div class="nextArrow slick-arrow slick-next">Next</div>
</div>
```
Is this always the default behavior? Can the arrow functionality not be set to target existing elements, similar to the original's settings? Any input/direction would be greatly appreciated!

**Comment by kyuwoo-choi** [comment]
you can use template to make custom arrows inside of the carousel.
but if you want to make the arrows outside of the carousel, you may want to use `prev`/`next` [API](https://github.com/gs-shop/vue-slick-carousel/blob/master/docs/API.md#all-methods) and `afterChange` [event](https://github.com/gs-shop/vue-slick-carousel/blob/master/docs/API.md#events)

**Comment by rshelnutt** [comment]
So to clarify: there is no method using template that will reposition the arrows within the carousel - they will always be rendered in the exact same position in the DOM when using this method. Is that correct?
