### ISSUE TITLE
Update Documentation: `focusOnSelect` default value does not seem to be false

### ISSUE THREAD

**Issue by haritha2112** [gs-shop/vue-slick-carousel#96]
Documentation mentions that `focusOnSelect` default value is false. But I had to set the property to be false in my settings for the carousel to actually not make it slide on slick. Looks like that value is set to true by default.

**Comment by kyuwoo-choi** [comment]
well. the default value of the `focusOnSelect` is `false` and I tested it works as I expected.
- no slide to the selected item by default
- slide to the selected item only when set the value to `true`

please reopen this issue you still have the problem or a specific steps to reproduce.
